name: Publish DevContainer Feature

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Install Devcontainers CLI
        run: npm install -g @devcontainers/cli

      - name: Publish Dev Container Features
        run: |
          devcontainer features publish \
            --collection-id "features" \
            --registry "ghcr.io" \
            --namespace "${{ github.repository_owner }}" \
            --password "${{ secrets.GH_PAT }}"

      - name: Done
        run: echo "Successfully published Dev Container Feature(s) to GHCR!"