name: "Release dev container features & Generate Documentation"
on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: auth gh
        run: echo "${{ secrets.GH_PAT }}" | gh auth login -p https --with-token

      - name: auth ghcr
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u HorseIncorporated --password-stdin

      - name: pre-build feature and publish
        run: devcontainers features publish --help